export const MOROCCAN_CITIES: string[] = [
  'Casablanca',
  'Rabat',
  'Marrakech',
  'Fès',
  'Tanger',
  'Agadir',
  'Meknès',
  'Oujda',
  'Kénitra',
  'Tétouan',
  'Safi',
  'El Jadida',
  'Nador',
  'Beni Mellal',
  'Mohammedia',
  'Khouribga',
  'Salé',
  'Témara',
  'Béni-Mellal',
  'Laâyoune',
  'Dakhla',
  'Essaouira',
  'Ouarzazate',
  'Errachidia',
  'Al Hoceïma',
  'Taza',
  'Settat',
  'Berrechid',
  'Taroudant',
  'Larache',
  'Ksar El Kebir',
  'Guelmim',
  'Fkih Ben Salah',
  'Sidi Kacem',
  'Midelt',
  'Tiflet',
  'Sefrou',
  'Youssoufia',
  'Azemmour',
  'Moulay Bousselham',
  'Berkane',
  'Taourirt',
  'Oulad Teïma',
  'Autre ville',
];
