export interface Fragrance {
  id: number;
  code: string;
  name: string;
  fullName: string;
  description: string;
  notes: string;
  badge?: string;
}

export const FRAGRANCES: Fragrance[] = [
  {
    id: 1,
    code: 'N°01',
    name: "L'EMPIRE",
    fullName: "NOVAIRE | N°01 | L'EMPIRE",
    description: "Inspiré par les notes iconiques d'Aventus",
    notes: "Ananas, Bergamote, Bois de Bouleau, Chêne",
    badge: "Bestseller",
  },
  {
    id: 2,
    code: 'N°02',
    name: "SILEX BLEU",
    fullName: "NOVAIRE | N°02 | SILEX BLEU",
    description: "Sillage intense boisé frais",
    notes: "Cèdre, Pamplemousse, Vetiver, Poivre Rose",
  },
  {
    id: 3,
    code: 'N°03',
    name: "BLEU ABSOLU",
    fullName: "NOVAIRE | N°03 | BLEU ABSOLU",
    description: "Élégance intemporelle aromatique",
    notes: "Menthe Fraîche, Citron, Encens, Santal",
  },
  {
    id: 4,
    code: 'N°04',
    name: "ABYSSAL",
    fullName: "NOVAIRE | N°04 | ABYSSAL",
    description: "Fraîcheur marine profonde",
    notes: "Notes Marines, Calone, Ambre Gris, Musc",
  },
  {
    id: 5,
    code: 'N°05',
    name: "AMBRE NOIR",
    fullName: "NOVAIRE | N°05 | AMBRE NOIR",
    description: "Chaleur envoûtante et gourmande",
    notes: "Ambre Précieux, Vanille Bourbon, Épices, Oud",
    badge: "Populaire",
  },
  {
    id: 6,
    code: 'N°06',
    name: "LINGOT D'OR",
    fullName: "NOVAIRE | N°06 | LINGOT D'OR",
    description: "Cuir épicé audacieux",
    notes: "Cuir, Mandarine Sangline, Cannelle, Rose",
  },
  {
    id: 7,
    code: 'N°07',
    name: "ROUGE CRISTAL",
    fullName: "NOVAIRE | N°07 | ROUGE CRISTAL",
    description: "Ambre rouge sophistiqué",
    notes: "Jasmin, Safran, Bois de Cèdre, Ambre Gris",
    badge: "Édition Limitée",
  },
  {
    id: 8,
    code: 'N°08',
    name: "NUIT NOIRE",
    fullName: "NOVAIRE | N°08 | NUIT NOIRE",
    description: "Café noir et vanille sensuelle",
    notes: "Café Torréfié, Fleurs Blanches, Vanille, Patchouli",
  },
  {
    id: 9,
    code: 'N°09',
    name: "TALONS ROUGES",
    fullName: "NOVAIRE | N°09 | TALONS ROUGES",
    description: "Tubéreuse mystérieuse et cacao",
    notes: "Tubéreuse, Cacao Pur, Fève Tonka, Amande",
  },
  {
    id: 10,
    code: 'N°10',
    name: "ÉCLAT JOYEUX",
    fullName: "NOVAIRE | N°10 | ÉCLAT JOYEUX",
    description: "Iris lumineux et gourmand",
    notes: "Iris de Florence, Praline, Cassis, Fleur d'Oranger",
  },
  {
    id: 11,
    code: 'N°11',
    name: "LIBRE ESPRIT",
    fullName: "NOVAIRE | N°11 | LIBRE ESPRIT",
    description: "Lavande audacieuse et fleur d'oranger",
    notes: "Lavande de Provence, Fleur d'Oranger, Mandarine, Musc",
  },
  {
    id: 12,
    code: 'N°12',
    name: "TENDRE CARESSE",
    fullName: "NOVAIRE | N°12 | TENDRE CARESSE",
    description: "Douceur fruitée-florale pétillante",
    notes: "Pêche Blanche, Rose de Mai, Pivoine, Bois Doux",
  },
];

export const PRICING_VARIANTS: Record<string, number> = {
  A: 299,
  B: 399,
  C: 499,
  a: 299,
  b: 399,
  c: 499,
};

export const MOROCCAN_CITIES: string[] = [
  "Casablanca",
  "Rabat",
  "Marrakech",
  "Fès",
  "Tanger",
  "Agadir",
  "Meknès",
  "Oujda",
  "Kénitra",
  "Tétouan",
  "Salé",
  "Mohammedia",
  "El Jadida",
  "Béni Mellal",
  "Nador",
  "Khémisset",
  "Settat",
  "Berrechid",
  "Larache",
  "Khouribga",
  "Guelmim",
  "Dakhla",
  "Laâyoune",
  "Safi",
  "Taroudant",
  "Taza",
  "Essaouira",
  "Al Hoceima",
  "Ksar El Kebir",
  "Sidi Kacem",
  "Tiznit",
  "Tan-Tan",
  "Ouarzazate",
  "Martil",
  "Midelt",
  "Errachidia",
  "Chefchaouen",
  "Azrou",
  "Ifrane",
  "Berkane",
  "Skhirat",
  "Bouskoura",
  "Dar Bouazza",
  "Autre ville / أخرى",
];
